#!/bin/bash
#
# Copyright 2023 Naive Systems Ltd.
#
# This software contains information and intellectual property that is
# confidential and proprietary to Naive Systems Ltd. and its affiliates.

# Usage: Print rule imports and switch cases in googlecpp/analyzer/run.go.

set -o errexit
set -o nounset
set -o pipefail

makeruleimports() {
        for line in $(<googlecpp_id)
        do
            rulenum=$(echo $line)
            echo -e "\\t\"naive.systems/analyzer/googlecpp/g${rulenum:1}\""
        done
        for line in $(<googlecpp_id)
        do
            rulenum=$(echo $line)
            cat <<EOF
		case "g${rulenum:1}":
			x(g${rulenum:1}.Analyze)
EOF
        done
}

makeruleimports "$@"

