#!/bin/bash
#
# Copyright 2023 Naive Systems Ltd.
#
# This software contains information and intellectual property that is
# confidential and proprietary to Naive Systems Ltd. and its affiliates.

# Usage: Generate googlecpp sub-folders with rule Analyze().

set -o errexit
set -o nounset
set -o pipefail

makeruledir() {
        if [[ -d "$1" ]]; then
                return
        fi
        mkdir -p "$1"
        cat >"$1/$1.go" <<EOF
/*
Copyright 2023 Naive Systems Ltd.

This software contains information and intellectual property that is
confidential and proprietary to Naive Systems Ltd. and its affiliates.
*/

package $1

import (
	pb "naive.systems/analyzer/analyzer/proto"
	"naive.systems/analyzer/cruleslib/options"
)

func Analyze(srcdir string, opts *options.CheckOptions) (*pb.ResultsList, error) {
	results := &pb.ResultsList{}
	return results, nil
}
EOF
}

makeruledirs() {
	cd "$(dirname "${BASH_SOURCE[0]}")/.."
        for line in $(<scripts/googlecpp_id)
        do
            rulenum=$(echo $line)
            makeruledir "g${rulenum:1}"
        done
}

makeruledirs "$@"

