#!/bin/bash
#
# Copyright 2022 Naive Systems Ltd.
#
# This software contains information and intellectual property that is
# confidential and proprietary to Naive Systems Ltd. and its affiliates.

set -o errexit
set -o nounset
set -o pipefail

makeruleimports() {
        for rule in `cat ./rulelist`
        do
            echo -e "\\t\"naive.systems/analyzer/misra_c_2012_crules/rule_${rule}\""
        done
        for rule in `cat ./rulelist`
        do
            cat <<EOF
		case "misra_c_2012/rule_${rule}":
		    x(rule_${rule}.Analyze(srcdir, &ruleOptions))
EOF
        done

}

makeruleimports "$@"
